apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pedidos-veloz

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - postgresdeployment.yaml
  - redis-deployment.yaml
  - rabbitmq-deployment.yaml
  - api-gateway-deployment.yaml
  - orders-service-deployment.yaml
  - inventory-service-deployment.yaml
  - payments-service-deployment.yaml
  - ingress.yaml
  - ../observability

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: pedidos-veloz