apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pedidos-veloz

secretGenerator:
  - name: pedidos-secrets
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - postgresdeployment.yaml
  - redis-deployment.yaml
  - rabbitmq-deployment.yaml
  - api-gateway-deployment.yaml
  - orders-service-deployment.yaml
  - inventory-service-deployment.yaml
  - payments-service-deployment.yaml
  - ingress.yaml
  - ../observability
  - ../security

labels:
  - pairs:
    includeSelectors: false

images:
  - name: pedidos-veloz-api-gateway
    newName: ghcr.io/devan-m/pedidos-veloz/api-gateway
  - name: pedidos-veloz-orders-service
    newName: ghcr.io/devan-m/pedidos-veloz/orders-service
  - name: pedidos-veloz-inventory-service
    newName: ghcr.io/devan-m/pedidos-veloz/inventory-service
  - name: pedidos-veloz-payments-service
    newName: ghcr.io/devan-m/pedidos-veloz/payments-service
