apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pedidos-veloz

resources:
  - prometheus-rbac.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
